#do updates
- name: Install all critical and security updates
  win_updates:
    category_names:
    - CriticalUpdates
    - SecurityUpdates
    - UpdateRollups
    - Updates
    - DefinitionUpdates
    state: installed
  register: update_result
  tags: update

- debug:
    var: update_result
  tags: update

- name: Reboot host if required
  win_reboot:
    reboot_timeout: 3600
  when: update_result.reboot_required
  tags: update
