---
# full list of windows features: http://geekswithblogs.net/Wchrabaszcz/archive/2013/09/04/how-to-install-windows-server-features-using-powershell--server.aspx
- name: Install IIS
  win_feature:
    name:
      - Web-Server
      # common
      - Web-Static-Content
      - Web-Default-Doc
      - Web-Http-Errors
      # performance
      - Web-Stat-Compression
      # security
      - Web-Filtering
      - Web-IP-Security
      - Web-Windows-Auth
      # health
      - Web-Http-Logging
      # application development
      - Web-Net-Ext45
      - Web-Asp-Net45
      - Web-CGI
      - Web-ISAPI-Ext
    state: present
    include_management_tools: True
  register: win_feature

- name: Reboot host if required
  win_reboot:
    reboot_timeout: 3600
  when: win_feature.reboot_required

#url max length
- name: edit max url length
  win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\HTTP\Parameters
      name: UrlSegmentMaxLength
      data: 520
      type: dword
  register: win_regedit

- name: Reboot host if required
  win_reboot:
    reboot_timeout: 3600
  when: win_regedit.changed

#tls stuff
#[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\Schannel\Protocols\SSL 2.0\Server]
#"Enabled"=dword:00000000
#"DisabledByDefault"=dword:00000001
#
#[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\Schannel\Protocols\SSL 3.0\Server]
#"Enabled"=dword:00000000
#"DisabledByDefault"=dword:00000001
#
#[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\Schannel\Protocols\TLS 1.0\Server]
#"Enabled"=dword:00000000
#"DisabledByDefault"=dword:00000001
#
#[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\Schannel\Protocols\TLS 1.1\Server]
#"Enabled"=dword:00000000
#"DisabledByDefault"=dword:00000001
#
#[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\Schannel\Protocols\TLS 1.2\Server]
#"Enabled"=dword:00000001
#"DisabledByDefault"=dword:00000000
#
##look on rp1 admin
