---

#- include: features.yml
#  when: type == 'webserver' or type == 'reverseProxy'

- include: mgmt.yml
  when: type == 'webserver' or type == 'reverseProxy'

- include: urlLength.yml
  when: type == 'webserver' or type == 'reverseProxy'

- include: tls.yml
  when: type == 'reverseProxy'

- include: user.yml
  when: type == 'webserver'

  #- include: virtualDir.yml
  #  when: type == 'webserver'


