---
- name: install IIS Remote Management Feature
  win_feature:
    name:
        - Web-Mgmt-Service
    state: present
    include_management_tools: True
  register: win_feature
  tags: management

- name: enable IIS Remote Management(WMSVC)
  win_regedit: 
      path: HKLM:\SOFTWARE\Microsoft\WebManagement\Server
      name: EnableRemoteManagement
      type: dword
      data: 1
  register: win_regedit
  tags: management

- name: activate IIS Remote Management(WMSVC)
  win_service:
    name: wmsvc
    start_mode: auto
    state: started
  tags: management

#https://ltcfaces.com/solution/remote-iis-management-in-windows-server-2016-2012-r2/
#make wmsvc work with tls1.2 WS2016
- name: enable remote management with tls1.2
  win_regedit: 
      path: HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
      name: SchUseStrongCrypto
      type: dword
      data: 1
  register: win_regedit
  tags: management

- name: enable remote management with tls1.2
  win_regedit: 
      path: HKLM:\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319
      name: SchUseStrongCrypto
      type: dword
      data: 1
  register: win_regedit
  tags: management

- name: Reboot host if required
  win_reboot:
    reboot_timeout: 3600
  when: win_regedit.changed
  tags: management


