---

#TLS 1.0
- name: check for tls1.0 key
  win_regedit:
      path: "{{ item }}"
      state: present
  with_items:
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client
  register: win_regedit1

- name: disable server tls 1.0
  win_regedit:
      path: "{{ item.path }}"
      name: "{{ item.name }}"
      data: "{{ item.data }}"
      type: "{{ item.type }}"
  loop:
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server', name: 'Enabled', data: 0, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client', name: 'Enabled', data: 0, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server', name: 'DisabledByDefault', data: 0, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client', name: 'DisabledByDefault', data: 0, type: 'dword' }
  register: win_regedit1enabled

#TLS 1.1
- name: check for tls1.1 keys
  win_regedit:
      path: "{{ item }}"
      state: present
  with_items:
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
  register: win_regedit11

- name: disable tls 1.1
  win_regedit:
      path: "{{ item.path }}"
      name: "{{ item.name }}"
      data: "{{ item.data }}"
      type: "{{ item.type }}"
  loop:
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server', name: 'Enabled', data: 0, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client', name: 'Enabled', data: 0, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server', name: 'DisabledByDefault', data: 0, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client', name: 'DisabledByDefault', data: 0, type: 'dword' }
  register: win_regedit11enabled

#TLS 1.2
- name: check for tls1.2 keys
  win_regedit:
      path: "{{ item }}"
      state: present
  with_items:
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server
      - HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
  register: win_regedit12

- name: enable tls 1.2
  win_regedit:
      path: "{{ item.path }}"
      name: "{{ item.name }}"
      data: "{{ item.data }}"
      type: "{{ item.type }}"
  loop:
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server', name: 'Enabled', data: 4294967295, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client', name: 'Enabled', data: 4294967295, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server', name: 'DisabledByDefault', data: 0, type: 'dword' }
      - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client', name: 'DisabledByDefault', data: 0, type: 'dword' }
  register: win_regedit12enabled

#enable secure ciphers
- name: enable secure ciphers
  win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Cryptography\Configuration\Local\SSL\00010002
      name: Functions
      type: multistring
      data:
          #recommandations BSI
        - TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
        - TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
        - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
        - TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
        - TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
        - TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
  register: win_regedit_cipher

- debug:
    var: win_regedit_cipher

- name: Reboot host if required
  win_reboot:
    reboot_timeout: 3600
  when: win_regedit1.results[0].changed or
        win_regedit1.results[1].changed or
        win_regedit1.results[2].changed or
        win_regedit11.results[0].changed or
        win_regedit11.results[1].changed or
        win_regedit11.results[2].changed or
        win_regedit12.results[0].changed or
        win_regedit12.results[1].changed or
        win_regedit12.results[2].changed or
        win_regedit1enabled.results[0].changed or
        win_regedit1enabled.results[1].changed or
        win_regedit1enabled.results[2].changed or
        win_regedit1enabled.results[3].changed or
        win_regedit11enabled.results[0].changed or
        win_regedit11enabled.results[1].changed or
        win_regedit11enabled.results[2].changed or
        win_regedit11enabled.results[3].changed or
        win_regedit12enabled.results[0].changed or
        win_regedit12enabled.results[1].changed or
        win_regedit12enabled.results[2].changed or
        win_regedit12enabled.results[3].changed or
        win_regedit_cipher.changed
