---
#url max length
- name: edit max url length
  win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\HTTP\Parameters
      name: UrlSegmentMaxLength
      data: 520
      type: dword
  register: win_regedit

- name: Reboot host if required
  win_reboot:
    reboot_timeout: 3600
  when: win_regedit.changed
